baseurl = "https://embraceyourduality.com"
title = "Embrace Your Duality"
author = "Jiamin Lei"
paginate = 3
theme = "arabica"

[params]
    description = "Data Visualization Portfolio using R"
    dateFormatToUse = "2006-01-02"
    replaceGoogleFonts = "fonts.loli.net"
 
